t=read.csv("spam.csv",stringsAsFactors = FALSE)
tail(t)
head(t)
summary(t)
t$v1=factor(t$v1)
str(t$v1)
library(tm)
text_mining=function(df){
  
  c= Corpus(VectorSource(df$v2))
  clean=tm_map(c,tolower)
  clean=tm_map(clean,removeNumbers)
 
  clean=tm_map(clean,removePunctuation)
  clean=tm_map(clean,stripWhitespace)
  clean=tm_map(clean,stemDocument)
  d=DocumentTermMatrix(clean)
  sd = removeSparseTerms(d, 0.95)
  textd = as.data.frame(as.matrix(sd))
  colnames(textd) = make.names(colnames(textd))
  textd$spam = df$v1
  textd$spam = as.factor(textd$spam)
  return(textd)
}
library(caTools)
set.seed(125)
textd=text_mining(t)
spl <- sample.split(textd$spam, 0.7)
train <- subset(textd, spl == TRUE)
test <- subset(textd,spl==FALSE)
library(e1071)
sms_classifier<- naiveBayes(train,train$spam,laplace=1)
sms_pred <- predict(sms_classifier,test)
library(gmodels)
CrossTable(sms_pred,test$spam,dnn = c("Predicted", "Actual"))
save(sms_classifier,file="NaiveBayesClassifier.rda")